version: 2
updates:
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: monthly
    groups:
      all-deps:
        patterns:
          - "*"
    open-pull-requests-limit: 1
