/** Site-wide configuration */
export const SITE = {
  name: "Maximilian Reinke",
  title: "Creating from the shadows",
  alias: "xi72yow",
  email: "max@reinke.ing",
  github: "xi72yow",
  githubUrl: "https://github.com/xi72yow",
  linkedin: "https://www.linkedin.com/in/maximilian-reinke-a0353630b/",
  catchphrase: "Lurking between embedded systems and web apps, between security tooling and Linux infrastructure. I build what's needed.",
  domain: "xi72yow.de",
  photoUrl: "/assets/avatar.webp",
} as const;

/** Movie quotes for the footer */
export const QUOTES = [
  ["gladiator", "are you not entertained?"],
  ["the dark knight", "why so serious?"],
  ["the fast and the furious", "i live my life a quarter mile at a time."],
  ["star wars", "i don't like sand. it's all coarse, and rough, and irritating. and it gets everywhere."],
  ["spider-man", "with great power comes great responsibility."],
  ["the lord of the rings", "you shall not pass!"],
  ["taken", "i have a very particular set of skills."],
  ["the social network", "a million dollars isn't cool. you know what's cool?"],
  ["mean girls", "she doesn't even go here!"],
  ["whiplash", "not quite my tempo."],
  ["the room", "you're tearing me apart, lisa!"],
  ["anchorman", "boy, that escalated quickly."],
  ["finding nemo", "just keep swimming."],
  ["elf", "you sit on a throne of lies."],
  ["napoleon dynamite", "you gonna eat your tots?"],
  ["zoolander", "what is this? a center for ants?"],
  ["step brothers", "it's the fucking catalina wine mixer."],
  ["harry potter", "you're a wizard, 'arry."],
  ["the prestige", "are you watching closely?"],
  ["cast away", "wilsoooooooon!"],
  ["get out", "now you're in the sunken place."],
  ["the notebook", "if you're a bird, i'm a bird."],
  ["national treasure", "i'm gonna steal the declaration of independence."],
  ["captain phillips", "look at me. i am the captain now."],
  ["borat", "my wife!"],
  ["legally blonde", "exercise gives you endorphins. endorphins make you happy."],
  ["the devil wears prada", "florals? for spring? groundbreaking."],
  ["there will be blood", "i drink your milkshake."],
  ["brokeback mountain", "i wish i knew how to quit you."],
  ["shrek", "ogres are like onions."],
  ["guardians of the galaxy", "i am groot."],
  ["three hundred", "this is sparta!"],
  ["training day", "king kong ain't got shit on me!"],
  ["the incredibles", "honey? where's my super suit?"],
  ["mad max fury road", "you will ride eternal, shiny and chrome."],
  ["inglourious basterds", "that's a bingo."],
  ["black panther", "is this your king?"],
  ["django unchained", "you had my curiosity. but now you have my attention."],
] as const;
